/** @type {import('tailwindcss').Config} */
export default {
  content: ['./index.html', './src/**/*.{js,ts,jsx,tsx}'],
  theme: {
    extend: {
      fontFamily: {
        sans: ['"Nunito Sans"', 'ui-sans-serif', 'system-ui'],
      },
      colors: {
        'brand-orange': '#FFA23B',
        'brand-blue': '#179BFF',
        'brand-navy': '#607DA9',
        'brand-yellow': '#FFD53B',
        'background-blue': '#E2EFFA',
        'background-green': '#E8FFE1',
        'gray-light': '#F2F2F2',
        'text-dark': '#262A33',
        'text-muted': '#6B7280',
        'success-green': '#48A96A',
        'error-red': '#EF4444',
        'border-gray': '#D1D5DB',
        'hover-blue': '#0F83D9',
        'cta-background': '#E6F4FF',
        'slate-blue': '#5C6B80',
        charcoal: '#4C4F54',
        'rich-black': '#1C1F23',
        'medium-gray': '#666666',
        'dark-gray': '#2E2E30',
        'pale-blue': '#E8F0FF',
        'accent-orange': '#FFB95E',
        carbon: '#474747',
        'forest-green': '#28964F',
        'light-gray': '#D9D9D9',
        blush: '#FBF0F1',
        crimson: '#D64550',
        'pale-sky': '#eaf3ff',
        'vivid-blue': '#3988FF',
        'indigo-blue': '#2563eb',
        'sky-blue': '#C6D9F5',
        'steel-gray': '#767676',
        snow: '#F4F7FC',
      },
      fill: (theme) => theme('colors'),
    },
  },
  plugins: [],
};
